include_guard(GLOBAL)

include(CMakeParseArguments)

# Initializes one aggregate clang-tidy target using the caller-provided command.
function(clang_tidy_init)
  cmake_parse_arguments(
    arg
    "QUIET"
    "CHECK_TARGET;EXECUTABLE;CONFIG;HEADER_FILTER"
    "CHECKS"
    ${ARGN}
  )
  if(arg_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "clang_tidy_init received unknown arguments: ${arg_UNPARSED_ARGUMENTS}")
  endif()
  get_property(initialized GLOBAL PROPERTY CLANG_TIDY_MODULE_INITIALIZED)
  if(initialized)
    message(FATAL_ERROR "clang_tidy_init may only be called once")
  endif()
  if(NOT arg_EXECUTABLE)
    message(FATAL_ERROR "clang_tidy_init requires EXECUTABLE")
  endif()
  if(NOT arg_CHECK_TARGET)
    message(FATAL_ERROR "clang_tidy_init requires CHECK_TARGET")
  endif()
  if(TARGET ${arg_CHECK_TARGET})
    message(FATAL_ERROR "clang-tidy aggregate target already exists: ${arg_CHECK_TARGET}")
  endif()

  set(tidy_command "${arg_EXECUTABLE}")
  if(arg_CHECKS)
    list(JOIN arg_CHECKS "," checks)
    list(APPEND tidy_command "-checks=${checks}")
  endif()
  if(arg_CONFIG)
    list(APPEND tidy_command "-config=${arg_CONFIG}")
  endif()
  if(arg_HEADER_FILTER)
    list(APPEND tidy_command "-header-filter=${arg_HEADER_FILTER}")
  endif()
  if(arg_QUIET)
    list(APPEND tidy_command --quiet)
  endif()

  add_custom_target(${arg_CHECK_TARGET})
  set_property(GLOBAL PROPERTY CLANG_TIDY_MODULE_INITIALIZED TRUE)
  set_property(GLOBAL PROPERTY CLANG_TIDY_MODULE_COMMAND "${tidy_command}")
  set_property(GLOBAL PROPERTY CLANG_TIDY_MODULE_CHECK_TARGET "${arg_CHECK_TARGET}")
endfunction()

# Enables clang-tidy for one compilation target and creates a scoped check target.
function(clang_tidy_enable)
  cmake_parse_arguments(arg "" "TARGET" "" ${ARGN})
  if(arg_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "clang_tidy_enable received unknown arguments: ${arg_UNPARSED_ARGUMENTS}")
  endif()
  get_property(initialized GLOBAL PROPERTY CLANG_TIDY_MODULE_INITIALIZED)
  if(NOT initialized)
    message(FATAL_ERROR "clang_tidy_enable requires clang_tidy_init")
  endif()
  if(NOT arg_TARGET OR NOT TARGET ${arg_TARGET})
    message(FATAL_ERROR "clang_tidy_enable requires an existing TARGET")
  endif()
  get_target_property(aliased_target ${arg_TARGET} ALIASED_TARGET)
  if(aliased_target)
    message(FATAL_ERROR "clang_tidy_enable cannot modify alias target: ${arg_TARGET}")
  endif()
  get_target_property(imported_target ${arg_TARGET} IMPORTED)
  if(imported_target)
    message(FATAL_ERROR "clang_tidy_enable cannot modify imported target: ${arg_TARGET}")
  endif()
  get_target_property(target_type ${arg_TARGET} TYPE)
  if(NOT target_type MATCHES "^(EXECUTABLE|STATIC_LIBRARY|SHARED_LIBRARY|MODULE_LIBRARY|OBJECT_LIBRARY)$")
    message(FATAL_ERROR "clang_tidy_enable requires a compilation target: ${arg_TARGET}")
  endif()
  get_property(aggregate_check GLOBAL PROPERTY CLANG_TIDY_MODULE_CHECK_TARGET)
  set(check_target "${arg_TARGET}-${aggregate_check}")
  if(TARGET ${check_target})
    message(FATAL_ERROR "clang-tidy target already exists for ${arg_TARGET}")
  endif()

  get_property(tidy_command GLOBAL PROPERTY CLANG_TIDY_MODULE_COMMAND)
  set_property(TARGET ${arg_TARGET} PROPERTY CXX_CLANG_TIDY "${tidy_command}")
  add_custom_target(${check_target} DEPENDS ${arg_TARGET})
  add_dependencies(${aggregate_check} ${check_target})
endfunction()
