set(MARKDOWN_FILES README.md)
file(GLOB_RECURSE DOC_MARKDOWN_FILES docs/*.md)
file(GLOB_RECURSE CONTAINER_MARKDOWN_FILES docker/*.md)
list(APPEND MARKDOWN_FILES ${DOC_MARKDOWN_FILES})
list(APPEND MARKDOWN_FILES ${CONTAINER_MARKDOWN_FILES})
list(SORT MARKDOWN_FILES)

include("${CMAKE_CURRENT_LIST_DIR}/uv.cmake")
uv_get_run_command(UV_RUN_COMMAND
    PROJECT_DIRECTORY "${PROJECT_SOURCE_DIR}"
)

set(MARKDOWN_TOOL_COMMAND
    ${UV_RUN_COMMAND}
    ${PROJECT_SOURCE_DIR}/tools/md.py
)

add_custom_target(markdown-format
    COMMENT "Formatting .md files"
    COMMAND ${MARKDOWN_TOOL_COMMAND} --mode=update ${MARKDOWN_FILES}
    WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
)

add_custom_target(markdown-format-check
    COMMENT "Verifying .md files are up-to-date"
    COMMAND ${MARKDOWN_TOOL_COMMAND} --mode=verify ${MARKDOWN_FILES}
    WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
)
