function(enable_sanitizers NS)
    string(TOUPPER "${CMAKE_BUILD_TYPE}" BUILD_TYPE)

    if (CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|MSVC" AND BUILD_TYPE MATCHES "DEBUG")
        option(${NS}_SANITIZER "enable sanitizers" ON)
    else()
        option(${NS}_SANITIZER "enable sanitizers" OFF)
    endif()

    option(${NS}_SANITIZER_TRAP "trap on sanitizer error" ON)
    if (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        set(${NS}_SANITIZER_OPTIONS "address;undefined;function" CACHE STRING "sanitizer options")
        set(${NS}_SANITIZER_OPTIMIZATION_LEVEL "-O1" CACHE STRING "optimization level used for sanitized targets")
    elseif (CMAKE_CXX_COMPILER_ID MATCHES "GNU")
        set(${NS}_SANITIZER_OPTIONS "address;undefined" CACHE STRING "sanitizer options")
        set(${NS}_SANITIZER_OPTIMIZATION_LEVEL "-O1" CACHE STRING "optimization level used for sanitized targets")
    elseif (CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
        set(${NS}_SANITIZER_OPTIONS "address")
    endif()

    if (${NS}_SANITIZER)
        if (CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
            # Override the build-type optimizer so sanitized development builds
            # stay practical to compile.
            add_compile_options(${${NS}_SANITIZER_OPTIMIZATION_LEVEL} -g -fno-omit-frame-pointer)
            if (CMAKE_CXX_COMPILER_ID MATCHES "Clang" AND ${NS}_SANITIZER_TRAP)
                add_compile_options(-fsanitize-trap=all)
            endif()
            foreach(arg ${${NS}_SANITIZER_OPTIONS})
                add_compile_options(-fsanitize=${arg})
                add_link_options(-fsanitize=${arg})
            endforeach()
        elseif (CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
            set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "ProgramDatabase")
            set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "ProgramDatabase" PARENT_SCOPE)
            foreach(arg ${${NS}_SANITIZER_OPTIONS})
                add_compile_options(/fsanitize=${arg})
            endforeach()
        else()
            message(FATAL_ERROR "sanitizers are not supported for ${CMAKE_CXX_COMPILER_ID}")
        endif()
    endif()
endfunction()
