"""Axis definitions for matrix test generation."""

from .containers import CONTAINERS
from .dependency_compositions import (
    DEPENDENCY_COMPOSITION_LEAVES,
    DEPENDENCY_COMPOSITION_OPERATORS,
    DEPENDENCY_COMPOSITION_REQUEST_STRATEGIES,
    DEPENDENCY_COMPOSITIONS,
)
from .dependency_forms import (
    DEPENDENCY_CARRIERS,
    DEPENDENCY_DECORATIONS,
    DEPENDENCY_FORMS,
    DEPENDENCY_PROVISIONINGS,
    DEPENDENCY_SHAPES,
)
from .exposed_types import EXPOSED_TYPES
from .feature_cases import FEATURE_CASES
from .features import FEATURES
from .modes import REGISTRATION_MODES
from .resolved_types import RESOLVED_TYPES
from .scopes import SCOPES, SHARED_CYCLICAL_SCOPE
from .shared_cyclical import (
    SHARED_CYCLICAL_CONTAINERS,
    SHARED_CYCLICAL_DEPENDENCY_EDGES,
    SHARED_CYCLICAL_DEPENDENCY_EDGE_SHAPES,
    SHARED_CYCLICAL_STORAGE_REPRESENTATIONS,
    SHARED_CYCLICAL_STORAGE_SHAPES,
)
from .stored_types import STORED_TYPES

__all__ = (
    "CONTAINERS",
    "DEPENDENCY_COMPOSITION_LEAVES",
    "DEPENDENCY_COMPOSITION_OPERATORS",
    "DEPENDENCY_COMPOSITION_REQUEST_STRATEGIES",
    "DEPENDENCY_COMPOSITIONS",
    "DEPENDENCY_CARRIERS",
    "DEPENDENCY_DECORATIONS",
    "DEPENDENCY_FORMS",
    "DEPENDENCY_PROVISIONINGS",
    "DEPENDENCY_SHAPES",
    "EXPOSED_TYPES",
    "FEATURES",
    "FEATURE_CASES",
    "REGISTRATION_MODES",
    "RESOLVED_TYPES",
    "SCOPES",
    "SHARED_CYCLICAL_CONTAINERS",
    "SHARED_CYCLICAL_DEPENDENCY_EDGES",
    "SHARED_CYCLICAL_DEPENDENCY_EDGE_SHAPES",
    "SHARED_CYCLICAL_SCOPE",
    "SHARED_CYCLICAL_STORAGE_REPRESENTATIONS",
    "SHARED_CYCLICAL_STORAGE_SHAPES",
    "STORED_TYPES",
)
