name: build
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  schedule:
    - cron: "0 0 * * *" # Daily
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yaml
