name: build-reusable
on:
  workflow_call:
    inputs:
      source_artifact_name:
        required: false
        type: string
        default: ''

jobs:
  build:
    uses: ./.github/workflows/build-base.yaml
    with:
      source_artifact_name: ${{ inputs.source_artifact_name }}
