name: build
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  schedule:
    - cron: "0 0 * * *" # Daily
  pull_request:
  push:
    branches:
      - master
env:
  BUILD_JOBS: ${{ vars.DINGO_BUILD_JOBS || '4' }}
jobs:
  linux:
    name: ${{ matrix.os }} / ${{ matrix.compiler.CXX }} / std-${{ matrix.compiler.STD }} / ${{ matrix.config.label }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        config:
          - id: Debug
            label: debug
          - id: Release
            label: release
        os: [ubuntu-24.04]
        compiler: [
          { CC: gcc-12, CXX: g++-12, STD: 17, SANITIZER: OFF },
          { CC: gcc-12, CXX: g++-12, STD: 20, SANITIZER: OFF },
          { CC: gcc-12, CXX: g++-12, STD: 23, SANITIZER: OFF },
          { CC: gcc-13, CXX: g++-13, STD: 17, SANITIZER: ON },
          { CC: gcc-13, CXX: g++-13, STD: 20, SANITIZER: ON },
          { CC: gcc-13, CXX: g++-13, STD: 23, SANITIZER: ON },
          { CC: gcc-14, CXX: g++-14, STD: 17, SANITIZER: ON },
          { CC: gcc-14, CXX: g++-14, STD: 20, SANITIZER: ON },
          { CC: gcc-14, CXX: g++-14, STD: 23, SANITIZER: ON },
          { CC: gcc-14, CXX: g++-14, STD: 26, SANITIZER: ON },
          { CC: clang-17, CXX: clang++-17, STD: 17, SANITIZER: ON },
          { CC: clang-17, CXX: clang++-17, STD: 20, SANITIZER: ON },
          #{ CC: clang-17, CXX: clang++-17, STD: 23, SANITIZER: ON },
          { CC: clang-18, CXX: clang++-18, STD: 17, SANITIZER: ON },
          { CC: clang-18, CXX: clang++-18, STD: 20, SANITIZER: ON },
          { CC: clang-18, CXX: clang++-18, STD: 23, SANITIZER: ON },
          { CC: clang-19, CXX: clang++-19, STD: 17, SANITIZER: ON },
          { CC: clang-19, CXX: clang++-19, STD: 20, SANITIZER: ON },
          { CC: clang-19, CXX: clang++-19, STD: 23, SANITIZER: ON },
          { CC: clang-19, CXX: clang++-19, STD: 26, SANITIZER: ON }
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: CCache
        uses: hendrikmuhs/ccache-action@v1.2.22
        with:
          key: ${{ matrix.os }}-${{ matrix.config.id }}-${{ matrix.compiler.CXX }}-${{ matrix.compiler.STD }}
          evict-old-files: job
      - name: Install Compiler
        run: |
            command -v ${{ matrix.compiler.CC }} >/dev/null || sudo apt-get install -y ${{ matrix.compiler.CC }}
            command -v ${{ matrix.compiler.CXX }} >/dev/null || sudo apt-get install -y ${{ matrix.compiler.CXX }}
      - name: Configure
        env:
            CXX: ${{ matrix.compiler.CXX }}
            CC: ${{ matrix.compiler.CC }}
        run: |
            cmake -S . -B build -DDINGO_DEVELOPMENT_MODE=ON -DDINGO_BENCHMARK_ENABLED=OFF -DDINGO_CCACHE=ON -DDINGO_TREAT_WARNINGS_AS_ERRORS=ON -DDINGO_SANITIZER=${{ matrix.compiler.SANITIZER }} -DCMAKE_BUILD_TYPE=${{ matrix.config.id }} -DCMAKE_CXX_STANDARD=${{ matrix.compiler.STD }}
      - name: Build
        run: |
            cmake --build build -j ${{ env.BUILD_JOBS }}
      - name: Test
        env:
          ASAN_OPTIONS: use_sigaltstack=false
        run: |
            cd build && ctest --verbose --output-on-failure
      - name: FetchContent
        run: |
            cmake -S test/fetchcontent -B fetchcontent-build -DCMAKE_BUILD_TYPE=${{ matrix.config.id }} -DCMAKE_CXX_STANDARD=${{ matrix.compiler.STD }}
            cmake --build fetchcontent-build -j ${{ env.BUILD_JOBS }}
      - name: Upload Failure Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4.6.2
        with:
          name: failure-${{ matrix.os }}-${{ matrix.compiler.CXX }}-std-${{ matrix.compiler.STD }}-${{ matrix.config.label }}
          if-no-files-found: ignore
          path: |
            build/CMakeFiles/CMakeOutput.log
            build/CMakeFiles/CMakeError.log
            build/Testing/Temporary
            fetchcontent-build/CMakeFiles/CMakeOutput.log
            fetchcontent-build/CMakeFiles/CMakeError.log

  windows:
    name: ${{ matrix.os }} / msvc / std-${{ matrix.std }} / ${{ matrix.config.label }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        config:
          - id: Debug
            label: debug
          - id: Release
            label: release
        os: [windows-2022, windows-2025]
        std: [17, 20, 23]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup MSVC Developer Command Prompt
        uses: TheMrMilchmann/setup-msvc-dev@v4.0.0
        with:
          arch: x64
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: CCache
        uses: hendrikmuhs/ccache-action@v1.2.22
        with:
          key: ${{ matrix.os }}-${{ matrix.config.id }}-${{ matrix.std }}
          evict-old-files: job
      - name: Configure
        run: |
            cmake -S . -B build -DDINGO_DEVELOPMENT_MODE=ON -DDINGO_BENCHMARK_ENABLED=OFF -DDINGO_CCACHE=ON -DDINGO_TREAT_WARNINGS_AS_ERRORS=ON -DCMAKE_BUILD_TYPE=${{ matrix.config.id }} -DCMAKE_CXX_STANDARD=${{ matrix.std }}
      - name: Build
        run: |
            cmake --build build --config ${{ matrix.config.id }} -j ${{ env.BUILD_JOBS }}
      - name: Test
        run: |
            cd build && ctest --verbose --output-on-failure -C ${{ matrix.config.id }}
      - name: FetchContent
        run: |
            cmake -S test/fetchcontent -B fetchcontent-build -DCMAKE_BUILD_TYPE=${{ matrix.config.id }} -DCMAKE_CXX_STANDARD=${{ matrix.std }}
            cmake --build fetchcontent-build -j ${{ env.BUILD_JOBS }}
      - name: Upload Failure Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4.6.2
        with:
          name: failure-${{ matrix.os }}-msvc-std-${{ matrix.std }}-${{ matrix.config.label }}
          if-no-files-found: ignore
          path: |
            build/CMakeFiles/CMakeOutput.log
            build/CMakeFiles/CMakeError.log
            build/Testing/Temporary
            fetchcontent-build/CMakeFiles/CMakeOutput.log
            fetchcontent-build/CMakeFiles/CMakeError.log
