name: lint-reusable
on:
  workflow_call:
    inputs:
      source_artifact_name:
        required: false
        type: string
        default: ''

jobs:
  check:
    uses: ./.github/workflows/check-base.yaml
    with:
      source_artifact_name: ${{ inputs.source_artifact_name }}
