name: windows-arm64-leg
on:
  workflow_call:
    inputs:
      source_artifact_name:
        required: false
        type: string
        default: ''
      vs_label:
        required: true
        type: string
      cross_runner:
        required: true
        type: string
      cross_generator:
        required: true
        type: string
      native_generator:
        required: true
        type: string
      config_id:
        required: true
        type: string
      config_label:
        required: true
        type: string
      std:
        required: true
        type: number

jobs:
  windows-arm64:
    uses: ./.github/workflows/windows-arm64.yaml
    with:
      source_artifact_name: ${{ inputs.source_artifact_name }}
      vs_label: ${{ inputs.vs_label }}
      cross_runner: ${{ inputs.cross_runner }}
      cross_generator: ${{ inputs.cross_generator }}
      native_generator: ${{ inputs.native_generator }}
      config_id: ${{ inputs.config_id }}
      config_label: ${{ inputs.config_label }}
      std: ${{ inputs.std }}
